import os
import asyncio
import time
import json
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from memory import FabMemory
from schema import SleepConsolidationOutput

load_dotenv()

# Setup structured Gemini LLM
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", api_key=os.getenv("GEMINI_API_KEY"))
structured_llm = llm.with_structured_output(SleepConsolidationOutput)

async def sleep_update_consolidator(section_id: str):
    """
    Background Worker: Extracts raw_logs, searches for matching consolidated SOPs,
    and runs incremental consolidation (Merge & Enrich) into long-term 'consolidated' memory.
    """
    memory_db = FabMemory()
    print(f"\nStarting Sleep Update for {section_id}...")
    
    # 1. Fetch raw logs
    logs = await memory_db.fetch_raw_logs(section_id)
    if not logs['documents']:
        print("No raw logs to consolidate.")
        return

    raw_content = "\n".join(logs['documents'])
    log_ids = logs['ids']

    # 2. Search for similar existing consolidated memories
    # Concatenate the first few raw logs to build a search query
    search_query = " ".join(logs['documents'][:3])
    similar_mems = await memory_db.search_similar_consolidated(section_id, search_query, n_results=3)
    
    existing_mems_str = "None"
    valid_ids = []
    if similar_mems:
        valid_ids = [m['id'] for m in similar_mems]
        existing_mems_str = "\n\n".join(
            f"ID: {m['id']}\nContent: {m['content']}" for m in similar_mems
        )

    # 3. 構建整合 Prompt (採用半導體專專家和使用繁體中文)
    current_time_ms = int(time.time() * 1000)
    prompt = f"""你是一位資深的半導體設備專家，專長於黃光、蝕刻與薄膜製程。
我們目前正在將新產生的原始設備事件日誌（Raw Logs）整合進入我們的長期知識庫（Consolidated SOPs）。

為了避免資料重複，並建立一個高品質、精煉的設備維護知識庫，你必須分析：
1. 【新原始日誌】中的所有事件，將它們按照【故障模式/Alarm型號】分類。你可以同時發現並分類多個不同的故障模式（例如：一個是 Dose 異常，另一個是 Heater block 故障）。
2. 【現有已固化SOP】（如果有的話），看看是否與本次發生的新事件屬於相同的設備故障模式。

【任務說明】
請為新日誌中識別出的【每一個不同故障模式】產生一個 `decisions` 陣列項目：
- 決策「is_merge」：
  * 如果該故障模式與某個現有SOP屬於【同一個故障模式/Alarm ID】（例如：同是 Dose Energy 異常，或同是 Heater block 故障），請將 `is_merge` 設為 `True`，並提供該 SOP 的 `existing_memory_id`。
  * 如果屬於全新的故障類型，請將 `is_merge` 設為 `False`，且 `existing_memory_id` 設為 null。
- 填充 `troubleshooting_data`：
  * 如果是 Merge（`is_merge = True`）：你需要將新日誌中的最新發現、新機台、更新後的維修方法或不同的工程師名單，**增量整合、融合**進原有的 SOP 中。調高或調低 `confidence_level`（若解決方案已被多次驗證，可更新為 'High - Confirmed SOP'）。
  * 如果是 Create（`is_merge = False`）：利用新日誌中的資訊，創立一條全新的、結構化 Troubleshooting SOP。
  * 確保 `process_area` 正確填寫（例如 {section_id}）。
  * `last_updated` 填寫當前的 Epoch 毫秒時間戳記：{current_time_ms}。

【現有已固化SOP】
{existing_mems_str}

【新原始日誌內容】
{raw_content}
"""

    # 4. Call LLM to reflect and consolidate using Pydantic schema
    print("Calling Gemini for structured consolidation reasoning...")
    response = await structured_llm.ainvoke(prompt)
    
    if not response.decisions:
        print("No consolidation decisions generated by LLM.")
        return

    # 5. Write to DB (either update/overwrite or create new) for each decision
    for dec in response.decisions:
        is_merge = dec.is_merge
        target_id = dec.existing_memory_id
        sop_data = dec.troubleshooting_data
        
        # Force the last_updated to current timestamp
        sop_data.last_updated = current_time_ms
        
        # Serialize to JSON string preserving Traditional Chinese characters
        sop_json = json.dumps(sop_data.model_dump(), ensure_ascii=False)

        if is_merge and target_id in valid_ids:
            print(f"Merging raw logs into existing consolidated memory (ID: {target_id})...")
            await memory_db.update_consolidated_memory(section_id, target_id, sop_json)
        else:
            print(f"Creating a brand new consolidated memory entry for [{sop_data.alarm_id}]...")
            await memory_db.add_consolidated_memory(section_id, sop_json)

    # 6. Prune raw logs
    await memory_db.delete_logs(section_id, log_ids)
    print(f"SUCCESS: Consolidated {len(log_ids)} logs into long-term memory for {section_id}.")

if __name__ == "__main__":
    asyncio.run(sleep_update_consolidator("PHOTO_LITHO_01"))
